name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: npm run build  # Adjust based on your build script

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "YourName"
          git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/Tarunbalaji2003/tarunbalaji.git
          npx gh-pages -d build/client
